version: '3.8'

services:
  backend:
    image: be:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://local:local@database:5432/spotify
    depends_on:
      - database
    networks:
      - backend-network

  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=spotify
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend-network

volumes:
  db_data:

networks:
  backend-network:
    driver: bridge