version: '3.8'

services:
  frontend:
    image: fe:latest
    ports:
      - "80:3000"  
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1
    networks:
      - app-network

  backend:
    image: be:latest
    ports:
      - "8080:8080" 
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node2
    environment:
      - DATABASE_URL=postgresql://local:local@spotify:5432/appdb
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=spotify
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node2
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: overlay 