version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: spotify
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - target: 5432
        published: 5434
        protocol: tcp
        mode: host
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local -d spotify"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - app-network
    deploy:
      placement:
        constraints:
          - node.role == manager 
      replicas: 1

  backend:
    image: 192.168.1.106:5000/be:latest
    ports:
      - target: 3003
        published: 3003
        protocol: tcp
        mode: host
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: spotify
      DB_USER: local
      DB_PASSWORD: local
      NODE_ENV: production
    networks:
      - app-network
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager 
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  frontend:
    image: 192.168.1.106:5000/fe:latest
    ports:
      - target: 5173
        published: 5173
        protocol: tcp
        mode: host
    environment:
      - VITE_API_URL=http://backend:3003
    networks:
      - app-network
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker  
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: overlay

volumes:
  db_data:
    driver: local